name: Build Windows Exe
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-node-version: '3.10'
    - name: Install Dependencies
      run: |
        pip install pygame pyinstaller
    - name: Build EXE
      run: |
        pyinstaller --onefile main.py
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows-exe
        path: dist/
